export enum CacheKeyType {
  ERC20_DECIMALS = 'ERC20_DECIMALS',

  V1_PRICE_BY_TOKENS = 'V1_PRICE_BY_TOKENS',
  V1_PRICE_BY_PAIR = 'V1_PRICE_BY_PAIR',
  V1_PAIR_TOKEN0 = 'V1_PAIR_TOKEN0',
  V1_PAIR_TOKEN1 = 'V1_PAIR_TOKEN1',

  V2_PRICE_BY_TOKENS = 'V2_PRICE_BY_TOKENS',
  V2_PRICE_BY_PAIR = 'V2_PRICE_BY_PAIR',

  V2_1_PRICE_BY_TOKENS = 'V2_1_PRICE_BY_TOKENS',
  V2_1_PRICE_BY_PAIR = 'V2_1_PRICE_BY_PAIR',
}
